name: chatsphere
description: "Connect with your friends with ChatSphere."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.0
  # Firebase
  firebase_app_check: ^0.2.1+19
  firebase_database: ^10.4.11
  cloud_firestore: ^4.15.10
  firebase_storage: ^11.6.10
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  # Icon
  flutter_launcher_icons: ^0.13.1
  # Google fonts
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700


# APP ICON
flutter_icons:
  image_path: assets/logo/app_logo.png
  android: "launcher_icon"
  ios: "AppIcon"
  remove_alpha_ios: true
  min_sdk_ios: 21