// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgEauGGu-PL-9Nmy5SvMjmMbaTwiwvD1k',
    appId: '1:299375821663:android:88a7e6c3b8cc3a14982cea',
    messagingSenderId: '299375821663',
    projectId: 'chatsphere-efefa',
    storageBucket: 'chatsphere-efefa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC3pfxrhVG3qjcg8-3UruiV4xwranijPo',
    appId: '1:299375821663:ios:eaea864ee2ef7e2f982cea',
    messagingSenderId: '299375821663',
    projectId: 'chatsphere-efefa',
    storageBucket: 'chatsphere-efefa.appspot.com',
    androidClientId: '299375821663-nqf9e2328p3b4gflfal2g4rpt3efduvh.apps.googleusercontent.com',
    iosClientId: '299375821663-gomac6nh8l89iog1rj8lktqqsj9fu31o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatsphere',
  );

}